apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-transmitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-transmitter
  template:
    metadata:
      labels:
        app: data-transmitter
    spec:
      containers:
      - name: data-transmitter
        image: <your_image_repository>/data-transmitter-service:latest  # Update with your image repository
        env:
        - name: PROJECT_ID
          valueFrom:
            secretRef:
              name: gcp-credentials  # Replace with your secret name
              key: project_id
        - name: BUCKET_NAME
          valueFrom:
            secretRef:
              name: gcp-credentials  # Replace with your secret name
              key: bucket_name
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
        volumeMounts:
        - name: shared-data
          mountPath: /shared
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data-pvc  # Adjust the PVC name
---
# Secret definition (replace with your actual values)
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
data:
  project_id: "<YOUR_PROJECT_ID_BASE64_ENCODED>"  # Base64-encode your project ID
  bucket_name: "<YOUR_BUCKET_NAME_BASE64_ENCODED>"  # Base64-encode your bucket name
type: Opaque

