apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-transmitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-transmitter
  template:
    metadata:
      labels:
        app: data-transmitter
    spec:
      containers:
      - name: data-transmitter
        image: northamerica-northeast2-docker.pkg.dev/kubetools-426513/traffik/data-transmission-service:0.2
        env:
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: gcp-credentials
              key: project_id
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: gcp-credentials
              key: bucket_name
        - name: GOOGLE_APPLICATION_CREDENTIALS  # Set the path to the service account key file
          value: /var/key.json
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        - name: google-cloud-key  # Mount for Google Cloud service account key
          mountPath: /var
          readOnly: true
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-data-pvc
      - name: google-cloud-key
        secret:
          secretName: your-google-cloud-secret-name  # Replace with the name of your secret
