apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc  # Adjust the PVC name
spec:
  accessModes:
    - ReadWriteOnce  # Adjust access mode if needed (e.g., ReadWriteMany)
  resources:
    requests:
      storage: 1Gi  # Adjust requested storage size
  storageClassName: standard  # Replace with your storage class name
